name = "camera-control-dashboard"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18"

[env.production]
name = "camera-control-dashboard-prod"

[env.staging]
name = "camera-control-dashboard-staging" 